# Generated by Django 3.2.25 on 2025-04-04 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='instagramlisting',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
