# Generated by Django 4.2.20 on 2025-05-20 09:21

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_instagramlisting_is_featured'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('proposed_price', models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
